/**
 * The branded loading screen. It shows the game's actual art — a real tile,
 * generated by the real generator — rather than a spinner, so the first frame a
 * player ever sees is Tideglass and not a starter template.
 */
import { useStore } from "../state/store.ts";
import { GAME_NAME, GAME_TAGLINE } from "../game/constants.ts";
import { makeKind } from "../game/mahjong/tiles.ts";
import TilePreview from "./TilePreview.tsx";

export default function LoadingScreen() {
    const progress = useStore((s) => s.loadProgress);
    // The shrine is only decoded partway through the warm, so the loading
    // screen deliberately does not depend on it — the mark and the title carry
    // the brand on their own if it has not arrived yet.
    return (
        <main className="loading-screen" aria-busy="true" aria-label={`${GAME_NAME} loading`}>
            <div className="loading-mark">
                <TilePreview kind={makeKind("creature", 2)} scale={3} />
            </div>
            <div className="loading-copy">
                <h1 className="loading-title">{GAME_NAME}</h1>
                <p className="loading-tagline">{GAME_TAGLINE}</p>
            </div>
            <div
                className="loading-bar"
                role="progressbar"
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={Math.round(progress * 100)}
            >
                <i style={{ width: `${Math.round(progress * 100)}%` }} />
            </div>
        </main>
    );
}
