/**
 * The three painted assets, imported so Vite fingerprints them and resolves
 * deployment-safe relative URLs.
 *
 * Everything else in Tideglass — every tile face, glyph, particle, panel and
 * sound — is still generated by the game's own code. These three exist because
 * generated gradients could not carry the atmosphere: a painted sunken shrine
 * and a real silted seabed do work that a `createLinearGradient` cannot.
 *
 * Both backdrops are JPEG because they are fully opaque; only the jellyfish,
 * which is composited over the results overlay, needs an alpha channel.
 */
import boardBackdropUrl from "./board-backdrop.jpg";
import lanternJellyUrl from "./lantern-jelly.png";
import menuBackdropUrl from "./menu-backdrop.jpg";

export const ART = {
    /** Sunken shrine. Menu, loading screen, and the frame behind the DOM UI. */
    menuBackdrop: menuBackdropUrl,
    /** Quiet silted seabed. Sits under the board; must never compete with tiles. */
    boardBackdrop: boardBackdropUrl,
    /** The lantern jellyfish that surfaces on a cleared level. */
    lanternJelly: lanternJellyUrl,
} as const;

export type ArtId = keyof typeof ART;

/** Decode an image so the first paint that uses it cannot pop. */
export function decodeArt(url: string): Promise<void> {
    return new Promise((resolve) => {
        const image = new Image();
        // Resolve on error too: a missing decorative image must never brick boot.
        image.onload = () => {
            void image.decode().then(
                () => resolve(),
                () => resolve(),
            );
        };
        image.onerror = () => resolve();
        image.src = url;
    });
}
