/**
 * Warming.
 *
 * Almost everything in Tideglass is generated by its own code, so most of what
 * the loading screen waits for is real work rather than network: painting the
 * thirty-six tile faces the board is about to need. The three painted
 * backdrops are decoded alongside them so the menu cannot pop in a beat after
 * it appears.
 *
 * Failure posture: nothing here may brick boot. A face that fails to paint
 * leaves an empty texture, a backdrop that fails to decode leaves the CSS
 * gradient behind it, and the game still runs.
 */
import { Assets } from "pixi.js";
import { ART, decodeArt } from "./art/index.ts";
import { warmTileArt } from "../game/art/tileArt.ts";
import { isFinishId } from "../game/art/finishes.ts";
import { store } from "../state/store.ts";

/** Matches the scale `boardScene` asks `createTileTextures` for. */
export function tileArtScale(): number {
    return Math.max(1, Math.min(3, Math.ceil(window.devicePixelRatio || 1)));
}

/**
 * @param onProgress 0..1, called as the faces are painted; always ends with a
 *   final call at 1.
 */
export async function warmAssets(onProgress: (progress: number) => void = () => {}): Promise<void> {
    const selected = store.get().selectedFinish;
    const finishId = isFinishId(selected) ? selected : "vitreum";

    try {
        // Reserve the tail of the bar for fonts, so the bar never sits at 100%
        // while the title is still waiting to swap.
        await warmTileArt(finishId, tileArtScale(), (progress) => onProgress(progress * 0.8));
    } catch (error) {
        console.warn("[preload] tile art warm failed — continuing without", error);
    }

    try {
        await Promise.all([
            // The seabed is drawn by Pixi, so it must be in PIXI's cache, not
            // just the browser's: `Texture.from(url)` is synchronous and returns
            // an empty texture for anything Assets has not loaded. The scene
            // sizes the sprite the moment it is created, so an empty texture
            // there means a permanently mis-scaled backdrop.
            Assets.load(ART.boardBackdrop),
            decodeArt(ART.menuBackdrop),
            decodeArt(ART.lanternJelly),
        ]);
        onProgress(0.92);
    } catch (error) {
        console.warn("[preload] backdrop load failed — continuing without", error);
    }

    // Wait for the display face so the first painted screen does not swap
    // fonts mid-frame under the title.
    try {
        await document.fonts.ready;
    } catch {
        /* older engines */
    }

    onProgress(1);
}
